name: Branch Push CI

on:
  schedule:
    - cron: '30 15,9 * * *'
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build --stacktrace --warning-mode=all
      - name: Grant execute permission for scripts/upload-apk.sh
        run: chmod +x scripts/upload-apk.sh
      - name: Deploy to Branch
        run: ./scripts/upload-apk.sh
        env:
          PAT: ${{ secrets.PAT }}
      - name: Grant execute permission for scripts/upload-app.sh
        run: chmod +x scripts/upload-app.sh
      - name: Deploy to Repo
        run: ./scripts/upload-app.sh
        env:
          PAT: ${{ secrets.PAT }}